extensions:
  - php
source:
  - ./framework
exclude:
  - "*prado-cli.php"
  - "*Vendor/*"
  - "*Javascripts/source/*"
  - "*packages.php"
  - "*JSMin.php"
  - "*I18N/core/*"
  - "*WebControls/assets/*"
  - "*Wsat/pages"
  - "*Wsat/themes"
destination: ./build/docs
annotationGroups:
  - todo
  - deprecated
groups: auto
title: Prado 4.0.1 API Manual
tree: true
version: true
sourceCode: no
overwrite: yes
templateConfig: ./vendor/pradosoft/prado-apigen-theme/src/config.neon